POST http://localhost:3333/todos HTTP/1.1
content-type: application/json

{
  "name":"task name 2",
  "done": false
}

###

GET http://localhost:3333/todos HTTP/1.1
content-type: application/json

###
PUT  http://localhost:3333/todos/1 HTTP/1.1
content-type: application/json

{
  "name":"task",
  "done":true
}

###
DELETE  http://localhost:3333/todos/2 HTTP/1.1
content-type: application/json